CC=gcc
LINKIN=-lpcap
CFLAGS=-Wall -pedantic -g
BASEDIR=..
SRCDIR=$(BASEDIR)/src
BUILDDIR=$(BASEDIR)/obj

etherscrape: etherscrape.o layer2.o util.o
	$(CC) $(CFLAGS) $(LINKIN) -o etherscrape \
		etherscrape.o layer2.o util.o

layer2.o: layer2.c
	$(CC) -c layer2.c -o $(BUILDDIR)\

util.o : util.c
	$(CC) -c util.c

clean:
	rm -rf *.o
